name: depthmap
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - tqdm
  - opencv
  - numpy
  - hydra-core
  - setuptools
  - pip:
    - omegaconf
